# Build settings
[build]
  base = "/client"
  publish = "/dist"
  command = "yarn build"

[build.environment]
  NODE_ENV = "production"

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin: *
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
