[build]
base = "/client"
publish = "/dist"
command = "yarn build"

[build.environment]
    NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "https://marketplace-server-69nj.onrender.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://reliable-belekoy-b39683.netlify.app/"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
